name = "ProgramAnalysis"
version = "0.1.0"
defaultTargets = ["programanalysis"]

[[lean_lib]]
name = "ProgramAnalysis"

[[lean_exe]]
name = "programanalysis"
root = "Main"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[require]]
name = "mathlib4"
scope = "leanprover-community"
rev = "v4.28.0"